### ISSUE TITLE
Upgrade from 5.0 to 5.1

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1236]
Prerequisites:

- [x] Dual boot: boot to Rails 5.0 by default
- [x] Fully migrate Rails 5.0 in production
- [x] Remove patches to support for Rails 4.2
- [ ] Enable new Rails 5.0 defaults
  - [ ] [Active Record belongs_to Required by Default Option](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-belongs-to-required-by-default-option)
  - [ ] [Per-form CSRF Tokens](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#per-form-csrf-tokens)
  - [ ] [Forgery Protection with Origin Check](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#forgery-protection-with-origin-check)
  - [ ] [Allow Configuration of Action Mailer Queue Name](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#allow-configuration-of-action-mailer-queue-name)
  - [ ] [Support Fragment Caching in Action Mailer Views](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#support-fragment-caching-in-action-mailer-views)
  - [ ] [Configure the Output of db:structure:dump](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-the-output-of-db-structure-dump)
  - [ ] [Configure SSL Options to Enable HSTS with Subdomains](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-ssl-options-to-enable-hsts-with-subdomains)
  - [ ] [Preserve Timezone of the Receiver](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#preserve-timezone-of-the-receiver)
- [ ] Fix Rails 5.0 deprecations (removed in Rails 5.1):
  - [ ] Upgrade `turbolinks` from 2.5 to 5.x
    - `before_filter` and `after_filter` have been removed in Rails 5.1
    - :warning: breaking changes (overall behavior)
    - :warning: `jquery-turbolinks` has been abandoned
  - [ ] Upgrade `react-rails` from 1.3 to ???:
    - `before_filter` and `after_filter` have been removed in Rails 5.1
    - sprockets method `register_engine` is deprecated
    - **problem**: requires to upgrade React to 0.14 (see #1842)
    - **alternative**: upgrade the JS pipeline to [webpacker](https://github.com/rails/webpacker) (deprecated in Rails 7) or [vite_rails](https://github.com/ElMassimo/vite_ruby).
  - [x] ~~fix and upgrade~~ drop `poirot_rails`:
    - `alias_method_chain` is deprecated, use `Module#prepend` instead

Upgrade:

- [ ] Dual boot to Rails 5.1 for next
- [ ] ...

References:

- See [Release Notes](https://guides.rubyonrails.org/5_1_release_notes.html)
- See [Upgrade Guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-0-to-rails-5-1)
- https://www.fastruby.io/blog/rails/upgrades/upgrade-rails-from-5-0-to-5-1.html
