### ISSUE TITLE
Improve the UX for users with QR code scanners

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1563]
**Goal**
Improve the experience when transferring samples for users that will be entering sample IDs by reading QR codes with scanning devices.

### User flow in real life
1. The technician receives an approved request to send specific samples to an external laboratory.  For instance: `100ml of the specimen role xxxxx with the inactivation method yyyyy`, `300ml of the specimen role zzzzz....`, etc.
2. The technician picks the samples from a freezer, puts them in a package, and the logistics company take it from there.

### Assumptions / Pre-requisites
1. The technician will have a QR code scanner connected into a device compatible with the CDx platform.
     1. It may be a QR code scanner plugged in a laptop or computer near the freezer where the samples are taken from.
     2. It may be a QR code scanner connected via bluetooth with a large tablet.

### Proposed Flow
1. The technician initiates a transfer screen in CDx.  
2. The technician selects the Institution (awardee) that the samples will be sent to.
3. The screen autofocus on a field for entering a sample ID.
4. The technician picks a sample from the freezer.
5. The technician scans the sample's QR code.
6. The scanner outputs the sample's id into the focused field.
7. CDx validates the sample's ID.
    1. If the sample's ID is correct, it's added into a list of samples being transferred, a success message appears, and the focus remains again on an empty field, ready for receiving the input of the next sample's id.
    2. If the sample's id is incorrect, an error message is shown, and the focus remains in the emptied field.  Some possible error messages are: `The sample ID xxxxxxx doesn't exist`, `The sample ID xxxxxx can't be added twice into the transferring list`, `The sample ID xxxxxx is associated to a QC sample which can't be transferred`.
8. Steps 4 through 7 are repeated until all the samples are selected.
9. The technician presses the transfer button in CDx.

### Sequence diagram
This [diagram](https://mermaid.live/edit#pako:eNqFk01r5DAMhv-K8GkLs_QDesmhUHZaKBQ6u1P2lIvGVmbMJLbXVro7W_rfKzdOU2b6EXCwpceW9Mp-VNobUpVK9Kcnp2lucR2xqx3IN_xRs49wT3rjrLboBmvAyLIM6Bh-zP8BJrjFwD7AcV4fQteR6D_FQ8dSo3PvORaot7imfPScWvtAcSf-F9vb_KbMvl9cSOgK7gI54IguNRQhaYnsPmKX1JJmsC6x5Z6td8f4F6OhEkOgEb3s2Tde90loSNiFluBmLovQc10CxHxYXK--nZ2czOBUxtn5-dHgA2i96BMpEDI0Iiqh3pSTRmQvx6JaBQurt5-jRcfqRVD4-Qtyaye2uMdibnLWok02mqmaiX9T-G9srUGmL7CrLvBukAMaS60BdDJG1fb3TMlLddE_WEPQEJmVtBg6Sum1zwellpshpcrVpD1ZyJlh-jr5qPeLKFGANwT342VZ9cy-9FLNVEexQ2vkgTxmW60E7qhWlUwNxm2tavckXB-yPlfGSj6qarBNNFO58uXOaVVx7GmEygsr1NMzOQEjMQ) describes the steps that will be followed by the technician at UCSD.

### Flow with business details
This [document](https://docs.google.com/document/d/1YlBYWeakAMFkzs_lI0zbWjGcdhksjZwvrMV8RfNkRxY/edit#heading=h.d22olv9ycdir) describes with some level of detail the business details in every step of the flow.

### Low fidelity PoC
https://user-images.githubusercontent.com/25181052/160403387-0a3ef3da-6b6c-4cc0-9328-f9cb75d6af22.mov

### Designs of the final feature
These designs include changes to the navigation, which are independent to the transfer feature, but that provide a better overall UX.

1. The Samples will be split into a [submenu](https://projects.invisionapp.com/d/main#/console/4103589/465509545/preview) of 3 options: individual samples, batches, transfers
2. The [split](https://projects.invisionapp.com/d/main#/console/4103589/453800852/preview) screen between samples and batches will not exist anymore.
3. The [right side-bar](https://projects.invisionapp.com/d/main#/console/4103589/453801739/preview) for navigating between samples/batches/transfers will not exist anymore.
4. The creation button in the Samples list will take you directly to create the sample.  The same goes for the batches list.
5. The [transfers view](https://projects.invisionapp.com/d/main#/console/4103589/465275288/preview) will have a main action button in the upper left corner.  
6. Previous action will present a [split](https://projects.invisionapp.com/d/main#/console/4103589/465275289/preview) between sending samples or confirming the receipt.
7. Transferring samples will present a [full page form](https://projects.invisionapp.com/d/main#/console/4103589/465342627/preview) (not a modal).
8. The [UI for confirming a receipt](https://projects.invisionapp.com/d/main#/console/4103589/465275296/preview) will also be in a full page form.

### Highlevel breakdown
1. Navigation changes: dropdown menu, creation of samples, batches, transfer form, right-side bar, probably etc
2. New full page form for transferring samples with the UX discussed for scanning devices.
3. New full page for confirming receipt with the UX discussed for scanning devices.
4. Adapt the flow for selecting samples and transferring, so that it uses the new full page form.
5. Remove the transferring/confirming receipt with Modals.
6. Autocomplete for improving keyboard experience.

**Comment by diegoliberman** [comment]
**Goal**
Improve the experience when transferring samples for users that will be entering sample IDs by reading QR codes with scanning devices.

### User flow in real life
1. The technician receives an approved request to send specified samples to an external laboratory.
2. The technician picks the samples from a fridge, puts them in a package, and the logistics company take it from there.

## Proposed flow with CDx

### Assumptions / Pre-requisites
1. The technician will have a QR code scanner connected into a device compatible with the CDx platform.
     1. It may be a QR code scanner plugged in a laptop or computer near the fridge where the samples are taken from.
     2. It may be a QR code scanner connected via bluetooth with a large tablet.

### Flow
1. The technician initiates a transfer screen in CDx.  The screen autofocus on a field for entering a sample ID.
2. The technician picks a sample from the Fridge.
3. The technician scans the sample's QR code.
4. The scanner outputs the sample's id into the focused field.
5. CDx validates the sample's ID.
    1. If the sample's ID is correct, it's added into a list of samples being transferred, and the focus remains again on an empty field, ready for receiving the input of the next sample's id.
    2. If the sample's id is incorrect, an error message is shown, and the focus remains in the emptied field.  Some possible error messages are: `The sample ID xxxxxxx doesn't exist`, `The sample ID xxxxxx can't be added twice into the transferring list`, `The sample ID xxxxxx is associated to a QC sample which can't be transferred`.

**Comment by ysbaddaden** [comment]
Some challenging thinking:

Maybe we don't need to ask the technician whether she wants to _send_ or _receive_ samples. She can start scanning a sample: if the sample is owned and currently not in-transfer, then we want to _send_ it to another institution, but if the sample is currently in-transfer, then we want to confirm the reception. It challenges @diegoliberman's take of selecting the destination institution first —which is still valid if we ask the technician what she wants to do (send or receive).

Shall we group transferred samples together, to represent some sort of package or parcel? Maybe we could already have an internal `parcel_id`, which would trivial to add, yet might come handy in the future? For example to present the technician with the list of samples she's expected to have received.

Let's try to break things down into sizeable chunks:

- [ ] 1. The navigation changes can be handled on their own (distinct issue);

- [ ] 2. Prerequisites:
  - [ ] add modal to select whether we want to send or receive samples + button trigger (prerequisite to below items);

- [ ] 3. change the "transfer samples" modal into a full page form:
  - [ ] step 1: no change in behavior (keep form, autocomplete, ...);
  - [ ] step 2:
    - [ ] add `samples#show` (JSON) to request a Sample by UUID (or use autocomplete?);
    - [ ] request sample when a valid UUID is scanned / typed / pasted;
    - [ ] validate the sample and either add it to the form, or display an error/notice message + clear input.

- [ ] 4. change the "confirm receipt" modal into a full page form:
  - [ ] add `sample_transfers#show` (JSON) to request a SampleTransfer by its Sample's UUID (consider an autocomplete?);
  - [ ] rework UI to request the Sample as we scan / type / paste a UUID;
  - [ ] add any valid Sample to the form and display an error for unexpected ones;
  - [ ] rework backend to confirm the reception of _many samples_ at once;
  - [ ] autocomplete the Sample UUID as we type it.

- [ ] 5. drop the original "confirm receipt" flow.

Once the prerequisite is done, the send and receive actions can be worked on in parallel.

**Comment by diegoliberman** [comment]
It's a good idea @ysbaddaden.  It's worth considering, as I guess that the frustrating scenario that I raised, could happen just once per institution:
1. The technician scans the samples.
2. When they pick the institution, it might not exist.  --> Frustration
3. Next time, they will make sure that institution exists.
4. From then on, normally, the institution will always be there.

For now, I think I will keep asking if it's a transfer or a confirmation.  Thinking that the first impressions are very important :)

However, you made me wonder: do we really need a pre-screen-modal for selecting transfer/receipt?  Both forms are very similar, the only difference is the institution field (and some feedback messages).  Couldn't we add a radio-button (or similar) as a first field in the form, to get the input of the action being done? If they select Transfer, we show the institutions field.  Else we hide it. 

cc @jkicillof

**Comment by ysbaddaden** [comment]
> However, you made me wonder: do we really need a pre-screen-modal for selecting transfer/receipt? Both forms are very similar, the only difference is the institution field (and some feedback messages).

From a technical point of view, they're actually quite different. We won't request the samples in the same way (sender: request _sample_, receiver: request _sample transfer_), and the actions are completely different (one creates sample transfer, the other confirms the transfer and moves the samples).

**Comment by nditada** [comment]
I think we are overcomplicating this and creating interaction patterns that are not common. Here's a simple approach:

1. We already have a screen to filter and search for samples. Let's use that.

2. Lets look at how the sample id needs to be made better to accept full barcodes typed from a scanner. Probably larger. 

3. Lets confirm UCSD barcode scanner can send a carriage return key after scanning, that should trigger the selection of the single item that we should have found when typing a complete barcode. 

4. We apply a search with selection UX pattern (take a look at how you build a broadcast list in WhatsApp for a good example of this interaction).  Let's simply keep the selected items at the top, with a check, maybe a darker background. Nothing too complicated. 

5. Add a bulk action menu for the selected items that enables initiating a transfer.

6. If the institution does not exist, there should be a "New Institution" that enables creating a quick stub with just enough data needed to continue the transfer.

**Comment by jkicillof** [comment]
> However, you made me wonder: do we really need a pre-screen-modal for selecting transfer/receipt? Both forms are very similar, the only difference is the institution field (and some feedback messages). Couldn't we add a radio-button (or similar) as a first field in the form, to get the input of the action being done? If they select Transfer, we show the institutions field. Else we hide it.

@diegoliberman if the user changes that after adding samples, all the samples should throw an error since they couldn't send something that they don't have or confirm something that they have already.

> Lets confirm UCSD barcode scanner can send a carriage return key after scanning, that should trigger the selection of the single item that we should have found when typing a complete barcode.

@nditada what happens if the user needs to send 30 samples? the filters are on top and each new element will appear farther from top (that if the selected items always appear on top and are not affected by the table sorting criteria). After some time the user won't be able to tell which one added at last. I feel the other pattern safer from the user point of view.

**Comment by jkicillof** [comment]
Furthermore I don't think filtering is the right pattern since we are not looking for people in a list were you know at least part of a name and then you choose one. We are looking for samples in a list were we won't be typing anything, we don't know the samples name and we expect just a single result.

**Comment by diegoliberman** [comment]
> 7. If the institution does not exist, there should be a "New Institution" that enables creating a quick stub with just enough data needed to continue the transfer.

I don't know how will this work.  A new institution can't be created without a user that is assigned as the super-admin.  And per the feature for inviting institution, I assume that the current user (UCSD) shouldn't be a user of the new institution (awardee).  We should then add the possibility of creating institutions that don't have a superuser, and we should also somehow allow to link a new/existent user as the super admin for the new institution.

Perhaps we can decide to make the current user the superadmin of the new institution.

Anyhow, we need to analyze how much effort will take both approaches.   If the effort is similar, I'd continue with the original proposal, as it will result in a better experience.

**Comment by ysbaddaden** [comment]
Yes, I prefer having an explicit actions and flow:

1. I want to send samples > I select a destination > I add the samples to transfer > I confirm;
2. I want to confirm receving samples > I scan the QR codes > I confirm —or maybe each sample is confirmed individually as it is scanned?

For starters, let's assume that the institution exists, that's much easier. Let's discuss this case in a dedicated enhancement issue, and have usage feedback from the client. I just believe more and more that we should have an internal `parcel_id` or `package_id` or something to group the samples, that will prove helpful.
