### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1792]
This is a long running epic to keep track of efforts to upgrade the major dependencies of CDx.

The list below is non exhaustive, items will probably be added as we upgrade and investigate the possibility to move on to the next item. It is, however, in the recommended order to follow.

**Preparations**
- [x] ~~upgrade to latest Rails 4.2.x~~ — done in #1511
- [x] ~~enabled dual boot~~ — done in #1549

**Rails 5**
- [x] ~~upgrade to Rails 5.0~~ —done in #1549
- [ ] upgrade to Ruby 2.3 —done in #1781
- [ ] upgrade to Ruby 2.4
- [ ] replace `therubyracer` gem —see #1790
- [ ] upgrade assets (blocks next Rails upgrade, because gems)
- [ ] upgrade to React 0.14 (blocks next Rails upgrade, because of `react-rails`)
- [ ] upgrade to Rails 5.1 —see #1236 
- [ ] upgrade to Ruby 2.5
- [ ] upgrade to Rails 5.2 —see #1237

**Rails 6**
- [ ] upgrade to Rails 6.0 (Maintained) —see #1238
- [ ] upgrade to Ruby 2.6
- [ ] upgrade to Rails 6.1 (Maintained)
- [ ] upgrade to Ruby 2.7 (EOL 2023/04)
- [ ] upgrade to Ruby 3.0 (Maintained)
